---
# FILE STRUCTURE
#
standard_files:
  rna: rna.pickle
  rna_r: rna.rds
  rna_ann: rna.anndata
file_map:
  normalize:
    corrected_umi: corrected_umi.mtx    # from sctransform
    pearson_residual: pearson_residuals.tsv    # from sctransform
  reduce:
    pca_embeddings: pca_embeddings.tsv
    pca_loadings: pca_loadings.tsv
    umap_embeddings: umap_embeddings.tsv
  cluster:
    clusters: clusters.tsv
  diffexp_bulk:
    diffexp_bulk_result: diffexp.tsv
  diffexp:
    diffexp_result: diffexp.tsv
  markers:
    markers: markers.tsv


# HOOKS
#   Hook will be collected recursively from directories or processes specified
#   in `hook_sources`. Hook containing files must be named `hooks.py`, and hook
#   functions names must begin with `hook_`.
#   (not tested on Windows)
#
#   hook_sources:
#     Paths to search recursively for hooks. Can be specified in module or
#     absolute path syntax.
#   setup_hooks: Hooks to run prior to process run.
#   clean_hooks: Hooks to run after process run.
hook_sources:
  - dataforest.hooks
  - cellforest.hooks
setup_hooks:
  - hook_comparative
  - hook_input_exists
  - hook_mkdirs
  - hook_store_temp_meta
clean_hooks:
  - hook_garbage_collection
  - hook_unify_matrix_node
  - hook_clean_temp_meta
  - hook_clean_unversioned
dataprocess_default_attrs:
  temp_meta: true
  matrix_layer: false

process_sources:
  - cellforest.processes
default_process_order:
  - normalize
  - reduce
  - cluster
  - diffexp
param_names:
  normalize:
    - max_genes
    - min_genes
    - perc_mito_cutoff
    - method
    - min_cells
    - nfeatures
  reduce:
    - pca_npcs
    - umap_n_neighbors
    - umap_min_dist
    - umap_n_components
    - umap_metric
  cluster:
    - res
    - eps
    - num_pcs
  diffexp_bulk:
    - logfc_thresh
    - test
  diffexp:
    - logfc_thresh
    - test
  markers:
    - logfc_thresh
    - test
  gsea:
    - gene_set
  gsea_bulk:
    - gene_set

r_filenames:
  LOAD_DATA_SCRIPT: load_data.R
  DIFF_EXP_BULK_SCRIPT: diff_exp_bulk.R
  DIFF_EXP_CLUSTER_SCRIPT: diff_exp_cluster_wise.R
  SCTRANSFORM_SCRIPT: run_sctransform.R
  PCA_SCRIPT: run_pca.R
  FIND_CLUSTERS_SCRIPT: find_clusters.R
  FIND_CLUSTER_MARKERS_SCRIPT: find_cluster_markers.R
  SEURAT_SCRIPT: run_seurat.R
  FUNCTIONS_FILE_PATH: functions.R
  SUBSET_RDS_SCRIPT: subset_rds.R
  FILTER_NORMALIZE_SCRIPT: filter_normalize.R
  SEURAT_DEFAULT_NORMALIZE_SCRIPT: seurat_default_normalize.R
r_scripts_module: cellforest.processes
temp_meta_filename: temp_meta.tsv